name: Run lint and static analyis checks
on:
  pull_request:
  workflow_call:

concurrency:
  group: lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  tardigradelint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Project Syntax Verification
        run: make docker/run target=lint

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Check workflow files
        uses: reviewdog/action-actionlint@7eeec1dd160c2301eb28e1568721837d084558ad
