name: Run test jobs
on:
  pull_request:
  workflow_call:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  mockstacktest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f

      - name: Install docker-compose
        run: make docker-compose/install

      - name: Start the mock AWS stack
        run: make mockstack/up

      - name: Apply Terraform test configs in mock AWS stack
        run: make mockstack/pytest

      - name: Cleanup the mock AWS stack
        run: make mockstack/clean
